server:
  port: 8082
logging:
  level:
    org.springframework.security: DEBUG
#  OAuth2 config
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:TEST-CLIENT-ID}
            client-secret:  ${GOOGLE_CLIENT_SECRET:TEST-CLIENT-SECRET}
            scope:
              - openid
              - profile
              - email
#            redirect-uri: http://localhost:8082/login/oauth2/code/google
          github:
            client-id: ${GITHUB_CLIENT_ID:TEST-CLIENT-ID}
            client-secret: ${GITHUB_CLIENT_SECRET:TEST-CLIENT-SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
security:
  jwt:
    secret: ${JWT_SECRET:ejfghGFegfGEFUWFGEFGGHUHG8hvhvefhgjsrhgerjgfdbdfb;FJYGEFYGJHABFhjgefyjegfyuEFHAEFJHJBFARHGGKABHAHJSVFHEJSVFHJEHFVJHSAVCHJACdsgfsdyg$jsfbhfbdhj}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}

app:
  cors:
    ui-url: http://localhost:5173
  auth:
    frontend:
      success-redirect: http://localhost:5173/auth/success
      failure-redirect: http://localhost:5173/auth/failure




